### ISSUE TITLE
Home.html should be changed to index.html so it is the default page

### ISSUE THREAD

**Issue by gwistix** [EduHubABC/EduHubABC.github.io#4]
By changing the name of `Home.html` to `index.html`, when a user visits EduHubABC.github.io, they will be directed to the home page rather than the `readme` file.

Other pages currently pointing to `Home.html` will need to be updated to point to `index.html`.

@EduHubABC What do you think?

**Comment by EduHubABC** [comment]
Alright then.  Sounds good.
